<?php

my_div_open(6, array ('class' => 'card shadow mb-4'));

my_div_open(7, array ('class' => 'card-section-group'));
my_div_open(8, array ('class' => 'card-header py-3 d-flex flex-row align-items-center justify-content-between clickable'));
my_inline_tag('h5', isset ($text) ? '' : 'Import Data Item Konfigurasi/Kategori Atribut', 9, array ('class' => 'm-0 font-weight-bold text-primary'));
my_div_close(8);
my_div_open(8, array ('class' => 'card-body collapsible'));
my_tag_open('form', 9, array ('role' => 'form', 'id' => 'form-import-assetci-attributes'));
my_div_open(10, array ('class' => 'row'));
my_div_open(11, array ('class' => 'col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12'));
my_div_open(12, array ('class' => 'form-group'));
my_inline_tag('label', isset ($text) ? '' : 'Unggah File Item Konfigurasi/Kategori Aset Atribut:', 13, array ('for' => 'file-import'));
my_div_open(13, array ('class' => 'input-group'));
my_div_open(14, array ('class' => 'input-group-prepend'));
my_tag_open('span', 15, array ('class' => 'input-group-text'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-file-alt fa-fw'));
my_tag_close('span', 15);
my_div_close(14);
my_input_tag('file', array ('class' => 'form-control collapsible', 'name' => 'file-import', 'accept' => 'text/csv,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel'), 14, TRUE);
my_input_tag('text', array ('class' => 'form-control', 'name' => 'file-import-label', 'readonly' => 'readonly'), 14);
my_div_open(14, array ('class' => 'input-group-append'));
my_tag_open('button', 15, array ('type' => 'button', 'name' => 'btn-browse-file', 'class' => 'btn btn-success', 'title' => isset ($text) ? '' : 'Pilih File'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-folder-open fa-fw'));
my_tag_close('button', 15);
my_tag_open('button', 15, array ('type' => 'button', 'name' => 'btn-cancel-file', 'class' => 'btn btn-danger', 'title' => isset ($text) ? '' : 'Batalkan'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-times fa-fw'));
my_tag_close('button', 15);
my_div_close(14);
my_div_close(13);
my_div_close(12);
my_div_close(11);
my_div_close(10);
my_div_open(10, array ('class' => 'row'));
my_div_open(11, array ('class' => 'col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12 text-right'));
my_tag_open('button', 12, array ('type' => 'button', 'name' => 'btn-upload-file', 'class' => 'btn btn-primary btn-icon-split', 'title' => isset ($text) ? '' : 'Unggah Berkas'));
my_tag_open('span', 13, array ('class' => 'icon text-white-50'));
my_inline_tag('i', '', 14, array ('class' => 'fas fa-upload fa-fw'));
my_tag_close('span', 13);
my_inline_tag('span', isset ($text) ? '' : 'Unggah', 13, array ('class' => 'text'));
my_tag_close('button', 12);
my_div_close(11);
my_div_close(10);
my_tag_close('form', 9);
my_div_close(8);
my_div_close(7);

my_div_open(7, array ('class' => 'card-section-group'));
my_div_open(8, array ('class' => 'card-header py-3 d-flex flex-row align-items-center justify-content-between clickable'));
my_inline_tag('h5', isset ($text) ? '' : 'Import Data Item Konfigurasi/Kategori', 9, array ('class' => 'm-0 font-weight-bold text-primary'));
my_div_close(8);
my_div_open(8, array ('class' => 'card-body collapsible'));
my_tag_open('form', 9, array ('role' => 'form', 'id' => 'form-import-assetci'));
my_div_open(10, array ('class' => 'row'));
my_div_open(11, array ('class' => 'col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12'));
my_div_open(12, array ('class' => 'form-group'));
my_inline_tag('label', isset ($text) ? '' : 'Unggah File Item Konfigurasi/Kategori:', 13, array ('for' => 'file-import'));
my_div_open(13, array ('class' => 'input-group'));
my_div_open(14, array ('class' => 'input-group-prepend'));
my_tag_open('span', 15, array ('class' => 'input-group-text'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-file-alt fa-fw'));
my_tag_close('span', 15);
my_div_close(14);
my_input_tag('file', array ('class' => 'form-control collapsible', 'name' => 'file-import', 'accept' => 'text/csv,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel'), 14, TRUE);
my_input_tag('text', array ('class' => 'form-control', 'name' => 'file-import-label', 'readonly' => 'readonly'), 14);
my_div_open(14, array ('class' => 'input-group-append'));
my_tag_open('button', 15, array ('type' => 'button', 'name' => 'btn-browse-file', 'class' => 'btn btn-success', 'title' => isset ($text) ? '' : 'Pilih File'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-folder-open fa-fw'));
my_tag_close('button', 15);
my_tag_open('button', 15, array ('type' => 'button', 'name' => 'btn-cancel-file', 'class' => 'btn btn-danger', 'title' => isset ($text) ? '' : 'Batalkan'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-times fa-fw'));
my_tag_close('button', 15);
my_div_close(14);
my_div_close(13);
my_div_close(12);
my_div_close(11);
my_div_close(10);
my_div_open(10, array ('class' => 'row'));
my_div_open(11, array ('class' => 'col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12 text-right'));
my_tag_open('button', 12, array ('type' => 'button', 'name' => 'btn-upload-file', 'class' => 'btn btn-primary btn-icon-split', 'title' => isset ($text) ? '' : 'Unggah Berkas'));
my_tag_open('span', 13, array ('class' => 'icon text-white-50'));
my_inline_tag('i', '', 14, array ('class' => 'fas fa-upload fa-fw'));
my_tag_close('span', 13);
my_inline_tag('span', isset ($text) ? '' : 'Unggah', 13, array ('class' => 'text'));
my_tag_close('button', 12);
my_div_close(11);
my_div_close(10);
my_tag_close('form', 9);
my_div_close(8);
my_div_close(7);

my_div_open(7, array ('class' => 'card-section-group'));
my_div_open(8, array ('class' => 'card-header py-3 d-flex flex-row align-items-center justify-content-between clickable'));
my_inline_tag('h5', isset ($text) ? '' : 'Import Data Penerima/Pengguna Aset', 9, array ('class' => 'm-0 font-weight-bold text-primary'));
my_div_close(8);
my_div_open(8, array ('class' => 'card-body collapsible'));
my_tag_open('form', 9, array ('role' => 'form', 'id' => 'form-import-loanees'));
my_div_open(10, array ('class' => 'row'));
my_div_open(11, array ('class' => 'col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12'));
my_div_open(12, array ('class' => 'form-group'));
my_inline_tag('label', isset ($text) ? '' : 'Unggah File Pengguna Aset:', 13, array ('for' => 'file-import'));
my_div_open(13, array ('class' => 'input-group'));
my_div_open(14, array ('class' => 'input-group-prepend'));
my_tag_open('span', 15, array ('class' => 'input-group-text'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-file-alt fa-fw'));
my_tag_close('span', 15);
my_div_close(14);
my_input_tag('file', array ('class' => 'form-control collapsible', 'name' => 'file-import', 'accept' => 'text/csv,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel'), 14, TRUE);
my_input_tag('text', array ('class' => 'form-control', 'name' => 'file-import-label', 'readonly' => 'readonly'), 14);
my_div_open(14, array ('class' => 'input-group-append'));
my_tag_open('button', 15, array ('type' => 'button', 'name' => 'btn-browse-file', 'class' => 'btn btn-success', 'title' => isset ($text) ? '' : 'Pilih File'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-folder-open fa-fw'));
my_tag_close('button', 15);
my_tag_open('button', 15, array ('type' => 'button', 'name' => 'btn-cancel-file', 'class' => 'btn btn-danger', 'title' => isset ($text) ? '' : 'Batalkan'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-times fa-fw'));
my_tag_close('button', 15);
my_div_close(14);
my_div_close(13);
my_div_close(12);
my_div_close(11);
my_div_close(10);
my_div_open(10, array ('class' => 'row'));
my_div_open(11, array ('class' => 'col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12 text-right'));
my_tag_open('button', 12, array ('type' => 'button', 'name' => 'btn-upload-file', 'class' => 'btn btn-primary btn-icon-split', 'title' => isset ($text) ? '' : 'Unggah Berkas'));
my_tag_open('span', 13, array ('class' => 'icon text-white-50'));
my_inline_tag('i', '', 14, array ('class' => 'fas fa-upload fa-fw'));
my_tag_close('span', 13);
my_inline_tag('span', isset ($text) ? '' : 'Unggah', 13, array ('class' => 'text'));
my_tag_close('button', 12);
my_div_close(11);
my_div_close(10);
my_tag_close('form', 9);
my_div_close(8);    
my_div_close(7);

my_div_open(7, array ('class' => 'card-section-group'));
my_div_open(8, array ('class' => 'card-header py-3 d-flex flex-row align-items-center justify-content-between clickable'));
my_inline_tag('h5', isset ($text) ? '' : 'Import Data Lokasi', 9, array ('class' => 'm-0 font-weight-bold text-primary'));
my_div_close(8);
my_div_open(8, array ('class' => 'card-body collapsible'));
my_tag_open('form', 9, array ('role' => 'form', 'id' => 'form-import-location'));
my_div_open(10, array ('class' => 'row'));
my_div_open(11, array ('class' => 'col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12'));
my_div_open(12, array ('class' => 'form-group'));
my_inline_tag('label', isset ($text) ? '' : 'Unggah File Lokasi:', 13, array ('for' => 'file-import'));
my_div_open(13, array ('class' => 'input-group'));
my_div_open(14, array ('class' => 'input-group-prepend'));
my_tag_open('span', 15, array ('class' => 'input-group-text'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-file-alt fa-fw'));
my_tag_close('span', 15);
my_div_close(14);
my_input_tag('file', array ('class' => 'form-control collapsible', 'name' => 'file-import', 'accept' => 'text/csv,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel'), 14, TRUE);
my_input_tag('text', array ('class' => 'form-control', 'name' => 'file-import-label', 'readonly' => 'readonly'), 14);
my_div_open(14, array ('class' => 'input-group-append'));
my_tag_open('button', 15, array ('type' => 'button', 'name' => 'btn-browse-file', 'class' => 'btn btn-success', 'title' => isset ($text) ? '' : 'Pilih File'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-folder-open fa-fw'));
my_tag_close('button', 15);
my_tag_open('button', 15, array ('type' => 'button', 'name' => 'btn-cancel-file', 'class' => 'btn btn-danger', 'title' => isset ($text) ? '' : 'Batalkan'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-times fa-fw'));
my_tag_close('button', 15);
my_div_close(14);
my_div_close(13);
my_div_close(12);
my_div_close(11);
my_div_close(10);
my_div_open(10, array ('class' => 'row'));
my_div_open(11, array ('class' => 'col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12 text-right'));
my_tag_open('button', 12, array ('type' => 'button', 'name' => 'btn-upload-file', 'class' => 'btn btn-primary btn-icon-split', 'title' => isset ($text) ? '' : 'Unggah Berkas'));
my_tag_open('span', 13, array ('class' => 'icon text-white-50'));
my_inline_tag('i', '', 14, array ('class' => 'fas fa-upload fa-fw'));
my_tag_close('span', 13);
my_inline_tag('span', isset ($text) ? '' : 'Unggah', 13, array ('class' => 'text'));
my_tag_close('button', 12);
my_div_close(11);
my_div_close(10);
my_tag_close('form', 9);
my_div_close(8);
my_div_close(7);

my_div_open(7, array ('class' => 'card-section-group'));
my_div_open(8, array ('class' => 'card-header py-3 d-flex flex-row align-items-center justify-content-between clickable'));
my_inline_tag('h5', isset ($text) ? '' : 'Import Data Sub Lokasi', 9, array ('class' => 'm-0 font-weight-bold text-primary'));
my_div_close(8);
my_div_open(8, array ('class' => 'card-body collapsible'));
my_tag_open('form', 9, array ('role' => 'form', 'id' => 'form-import-sublocation'));
my_div_open(10, array ('class' => 'row'));
my_div_open(11, array ('class' => 'col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12'));
my_div_open(12, array ('class' => 'form-group'));
my_inline_tag('label', isset ($text) ? '' : 'Unggah File Sublokasi:', 13, array ('for' => 'file-import'));
my_div_open(13, array ('class' => 'input-group'));
my_div_open(14, array ('class' => 'input-group-prepend'));
my_tag_open('span', 15, array ('class' => 'input-group-text'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-file-alt fa-fw'));
my_tag_close('span', 15);
my_div_close(14);
my_input_tag('file', array ('class' => 'form-control collapsible', 'name' => 'file-import', 'accept' => 'text/csv,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel'), 14, TRUE);
my_input_tag('text', array ('class' => 'form-control', 'name' => 'file-import-label', 'readonly' => 'readonly'), 14);
my_div_open(14, array ('class' => 'input-group-append'));
my_tag_open('button', 15, array ('type' => 'button', 'name' => 'btn-browse-file', 'class' => 'btn btn-success', 'title' => isset ($text) ? '' : 'Pilih File'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-folder-open fa-fw'));
my_tag_close('button', 15);
my_tag_open('button', 15, array ('type' => 'button', 'name' => 'btn-cancel-file', 'class' => 'btn btn-danger', 'title' => isset ($text) ? '' : 'Batalkan'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-times fa-fw'));
my_tag_close('button', 15);
my_div_close(14);
my_div_close(13);
my_div_close(12);
my_div_close(11);
my_div_close(10);
my_div_open(10, array ('class' => 'row'));
my_div_open(11, array ('class' => 'col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12 text-right'));
my_tag_open('button', 12, array ('type' => 'button', 'name' => 'btn-upload-file', 'class' => 'btn btn-primary btn-icon-split', 'title' => isset ($text) ? '' : 'Unggah Berkas'));
my_tag_open('span', 13, array ('class' => 'icon text-white-50'));
my_inline_tag('i', '', 14, array ('class' => 'fas fa-upload fa-fw'));
my_tag_close('span', 13);
my_inline_tag('span', isset ($text) ? '' : 'Unggah', 13, array ('class' => 'text'));
my_tag_close('button', 12);
my_div_close(11);
my_div_close(10);
my_tag_close('form', 9);
my_div_close(8);
my_div_close(7);

my_div_open(7, array ('class' => 'card-section-group'));
my_div_open(8, array ('class' => 'card-header py-3 d-flex flex-row align-items-center justify-content-between clickable'));
my_inline_tag('h5', isset ($text) ? '' : 'Import Data Status Aset', 9, array ('class' => 'm-0 font-weight-bold text-primary'));
my_div_close(8);
my_div_open(8, array ('class' => 'card-body collapsible'));
my_tag_open('form', 9, array ('role' => 'form', 'id' => 'form-import-asset-status'));
my_div_open(10, array ('class' => 'row'));
my_div_open(11, array ('class' => 'col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12'));
my_div_open(12, array ('class' => 'form-group'));
my_inline_tag('label', isset ($text) ? '' : 'Unggah File Status Aset:', 13, array ('for' => 'file-import'));
my_div_open(13, array ('class' => 'input-group'));
my_div_open(14, array ('class' => 'input-group-prepend'));
my_tag_open('span', 15, array ('class' => 'input-group-text'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-file-alt fa-fw'));
my_tag_close('span', 15);
my_div_close(14);
my_input_tag('file', array ('class' => 'form-control collapsible', 'name' => 'file-import', 'accept' => 'text/csv,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel'), 14, TRUE);
my_input_tag('text', array ('class' => 'form-control', 'name' => 'file-import-label', 'readonly' => 'readonly'), 14);
my_div_open(14, array ('class' => 'input-group-append'));
my_tag_open('button', 15, array ('type' => 'button', 'name' => 'btn-browse-file', 'class' => 'btn btn-success', 'title' => isset ($text) ? '' : 'Pilih File'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-folder-open fa-fw'));
my_tag_close('button', 15);
my_tag_open('button', 15, array ('type' => 'button', 'name' => 'btn-cancel-file', 'class' => 'btn btn-danger', 'title' => isset ($text) ? '' : 'Batalkan'));
my_inline_tag('i', '', 16, array ('class' => 'fas fa-times fa-fw'));
my_tag_close('button', 15);
my_div_close(14);
my_div_close(13);
my_div_close(12);
my_div_close(11);
my_div_close(10);
my_div_open(10, array ('class' => 'row'));
my_div_open(11, array ('class' => 'col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12 text-right'));
my_tag_open('button', 12, array ('type' => 'button', 'name' => 'btn-upload-file', 'class' => 'btn btn-primary btn-icon-split', 'title' => isset ($text) ? '' : 'Unggah Berkas'));
my_tag_open('span', 13, array ('class' => 'icon text-white-50'));
my_inline_tag('i', '', 14, array ('class' => 'fas fa-upload fa-fw'));
my_tag_close('span', 13);
my_inline_tag('span', isset ($text) ? '' : 'Unggah', 13, array ('class' => 'text'));
my_tag_close('button', 12);
my_div_close(11);
my_div_close(10);
my_tag_close('form', 9);
my_div_close(8);
my_div_close(7);

my_div_close(6);
